name: Node.js CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          npm install

      - name: Run tests
        run: |
          echo "Running tests..."
          npm test

      - name: Deploy to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_KEY: ${{ secrets.EC2_KEY }}
        run: |
          echo "Deploying to EC2..."
          # Write the private key to a file
          echo "$EC2_KEY" > deploy_key.pem
          chmod 600 deploy_key.pem

          # SSH into the EC2 instance and deploy
          ssh -o StrictHostKeyChecking=no -i deploy_key.pem $EC2_USER@$EC2_HOST "cd /home/ubuntu/your-repo-name && git pull origin main && npm install && pm2 restart my-node-app"
